[animations]

[animations.window-open-close]
curve = "ease-out-expo"
duration = 250

[animations.workspace-switch]
curve = "ease-out-expo"
duration = 150

[animations.window-geometry]
disable = true

