[keybinds] 
Super-q = "quit"
Super-c = "close-focused-window"
Super-f = "fullscreen-focused-window"
Super-m = "maximize-focused-window"
Super-Ctrl-Space = "float-focused-window"
Super-Ctrl-r = "reload-config"
Super-j = "focus-next-window"
Super-k = "focus-previous-window"

Super-Return = { action = "run-command", arg = "wezterm" } # terminal
Super-e = {action = "run-command", arg = "thunar"} # filemanager
Super-b = {action = "run-command", arg = "microsoft-edge-stable"} # browser
Super-n = {action = "run-command", arg = "swaync-client -t -sw"} # notif

# workspace management stuff
Super-1 = { action = "focus-workspace", arg = 0 }
Super-2 = { action = "focus-workspace", arg = 1 }
Super-3 = { action = "focus-workspace", arg = 2 }
Super-4 = { action = "focus-workspace", arg = 3 }
Super-5 = { action = "focus-workspace", arg = 4 }
Super-6 = { action = "focus-workspace", arg = 5 }
Super-7 = { action = "focus-workspace", arg = 6 }
Super-8 = { action = "focus-workspace", arg = 7 }
Super-9 = { action = "focus-workspace", arg = 8 }

Super-Ctrl-1 = { action = "send-to-workspace", arg = 0 }
Super-Ctrl-2 = { action = "send-to-workspace", arg = 1 }
Super-Ctrl-3 = { action = "send-to-workspace", arg = 2 }
Super-Ctrl-4 = { action = "send-to-workspace", arg = 3 }
Super-Ctrl-5 = { action = "send-to-workspace", arg = 4 }
Super-Ctrl-6 = { action = "send-to-workspace", arg = 5 }
Super-Ctrl-7 = { action = "send-to-workspace", arg = 6 }
Super-Ctrl-8 = { action = "send-to-workspace", arg = 7 }
Super-Ctrl-9 = { action = "send-to-workspace", arg = 8 }


[keybinds.XF86AudioRaiseVolume]
action = "run-command"
arg = "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
allow-while-locked = true
repeat = true

[keybinds.XF86AudioLowerVolume]
action = "run-command"
arg = "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%-"
allow-while-locked = true
repeat = true

[keybinds.XF86AudioMute]
action = "run-command"
arg = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
allow-while-locked = true
repeat = true


[keybinds.XF86AudioMicMute]
action = "run-command"
arg = "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
allow-while-locked = true

[keybinds.XF86MonBrightnessUp]
action = "run-command"
arg = "brightnessctl -e4 -n2 set 5%+"
allow-while-locked = true
repeat = true

[keybinds.XF86MonBrightnessDown]
action = "run-command"
arg = "brightnessctl -e4 -n2 set 5%-"
allow-while-locked = true
repeat = true

[mousebinds]
Super-Left = "swap-tile"
Super-Right = "resize-tile"
Super-Scrollup = "focus-next-workspace"
Super-Scrolldown = "focus-previous-workspace"