[decorations]
decoration-mode = "force-server-side"

[decorations.border]
thickness = 2 
radius = 10
focused-color = "#18D5DC"
normal-color = "transparent"

[decorations.shadow]
floating-only = true
sigma = 10.0
color = "rgba(black, 0.75)"
