[input.keyboard]
layout = "us"
rules = ""
repeat-rate = 25
repeat-delay = 250

[input.touchpad]
acceleration-profile = "adaptive"
scroll-method = "two-finger"
natural-scrolling = true
tap-and-drag = true
tap-to-click = true
click-method = "click-finger"

[input.mouse]
acceleration-profile = "linear"